#!/usr/bin/env python
# -*- codint: utf-8 -*-

import sys
import signal
import subprocess

def rite(silent):
    print("start rite of gulp watch be zombie")
    print("if you want stop this program, Ctrl+C")
    cmd = "gulp"
    while True:
        p = subprocess.Popen(cmd, shell=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        for line in iter(p.stdout.readline, b''):
            print(line.rstrip())
        if not silent:
            print("\a")
        print("\ngulp watch is dead. but revive soon.\n")

def signalHandler(signal, frame):
    print("\ngulp zombie killed")
    sys.exit(0)

if __name__ == '__main__':
    signal.signal(signal.SIGINT, signalHandler)
    try:
        sys.argv.index("-s")
        rite(True)
    except ValueError:
        rite(False)
